name: Find changes

on:
  workflow_call:
    inputs:
      working_dir:
        required: true
        description: "Path of root to check for changes."
        type: string
        default: "modules/"
    secrets:
      OVERRIDE_TOKEN:
        required: false

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.find_changes.outputs.changes }}
    steps:
      # This checkout is for credentials
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} #TODO: Add toggle for override token
          sparse-checkout: .github

      - name: Find changes in branch
        id: find_changes
        run: |
          changes=$(git diff --name-only ${{ github.ref }} HEAD^ ${{ inputs.working_dir }} | awk -F'/' '{print $1}' | uniq)
          json="{\"changes\":[$(echo $changes | sed -e 's/ /","/g')]}"
          echo "changes=$json" >> $GITHUB_OUTPUT

      - name: Print JSON output
        run: echo "${{ steps.find_changes.outputs.json }}"